name: Convol build

on:
  push:
    workflow_dispatch:
    branches:
      '**'
    pull_request: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tools
        run: sudo apt-get update && sudo apt-get install -y clang-tools && sudo apt-get install -y libomp-dev

      - name: Run clang-tidy
        run: make lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check formatting
        run: make fmt-check

  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cmocka
        run: sudo apt-get update && sudo apt-get install -y clang-format && sudo apt-get install -y libcmocka-dev

      - name: Run tests
        run: make test